#EscapeChar \

#IfWinNotActive ahk_class VMUIFrame

; Modifiers
  $*LControl::      PressKeyEvent(   "LControl" )
  $*LControl Up::   ReleaseKeyEvent( "LControl" )
  $*LShift::        PressKeyEvent(   "LShift" )
  $*LShift Up::     ReleaseKeyEvent( "LShift" )
  $*LAlt::          PressKeyEvent(   "LAlt" )
  $*LAlt Up::       ReleaseKeyEvent( "LAlt" )
  $*LWin::          PressKeyEvent(   "LWin" )
  $*LWin Up::       ReleaseKeyEvent( "LWin" )
  $*RControl::      PressKeyEvent(   "RControl" )
  $*RControl Up::   ReleaseKeyEvent( "RControl" )
  $*RShift::        PressKeyEvent(   "RShift" )
  $*RShift Up::     ReleaseKeyEvent( "RShift" )
  $*RAlt::          PressKeyEvent(   "RAlt" )
  $*RAlt Up::       ReleaseKeyEvent( "RAlt" )


; Normal Keys
  ; Left Hand
  $*Escape::        PressKeyEvent(   "Escape" )
  $*Escape Up::     ReleaseKeyEvent( "Escape" )
  $*`::             PressKeyEvent(   "`" )
  $*` Up::          ReleaseKeyEvent( "`" )
  $*Tab::           PressKeyEvent(   "Tab" )
  $*Tab Up::        ReleaseKeyEvent( "Tab" )
  $*1::             PressKeyEvent(   "1" )
  $*1 Up::          ReleaseKeyEvent( "1" )
  $*2::             PressKeyEvent(   "2" )
  $*2 Up::          ReleaseKeyEvent( "2" )
  $*3::             PressKeyEvent(   "3" )
  $*3 Up::          ReleaseKeyEvent( "3" )
  $*4::             PressKeyEvent(   "4" )
  $*4 Up::          ReleaseKeyEvent( "4" )
  $*5::             PressKeyEvent(   "5" )
  $*5 Up::          ReleaseKeyEvent( "5" )
  $*6::             PressKeyEvent(   "6" )
  $*6 Up::          ReleaseKeyEvent( "6" )
  $*'::             PressKeyEvent(   "'" )
  $*' Up::          ReleaseKeyEvent( "'" )
  $*,::             PressKeyEvent(   "," )
  $*, Up::          ReleaseKeyEvent( "," )
  $*.::             PressKeyEvent(   "." )
  $*. Up::          ReleaseKeyEvent( "." )
  $*p::             PressKeyEvent(   "p" )
  $*p Up::          ReleaseKeyEvent( "p" )
  $*y::             PressKeyEvent(   "y" )
  $*y Up::          ReleaseKeyEvent( "y" )
  $*a::             PressKeyEvent(   "a" )
  $*a Up::          ReleaseKeyEvent( "a" )
  $*o::             PressKeyEvent(   "o" )
  $*o Up::          ReleaseKeyEvent( "o" )
  $*e::             PressKeyEvent(   "e" )
  $*e Up::          ReleaseKeyEvent( "e" )
  $*u::             PressKeyEvent(   "u" )
  $*u Up::          ReleaseKeyEvent( "u" )
  $*i::             PressKeyEvent(   "i" )
  $*i Up::          ReleaseKeyEvent( "i" )
  $*;::             PressKeyEvent(   ";" )
  $*; Up::          ReleaseKeyEvent( ";" )
  $*q::             PressKeyEvent(   "q" )
  $*q Up::          ReleaseKeyEvent( "q" )
  $*j::             PressKeyEvent(   "j" )
  $*j Up::          ReleaseKeyEvent( "j" )
  $*k::             PressKeyEvent(   "k" )
  $*k Up::          ReleaseKeyEvent( "k" )
  $*x::             PressKeyEvent(   "x" )
  $*x Up::          ReleaseKeyEvent( "x" )

  ; Right Hand
  $*7::             PressKeyEvent(   "7" )
  $*7 Up::          ReleaseKeyEvent( "7" )
  $*8::             PressKeyEvent(   "8" )
  $*8 Up::          ReleaseKeyEvent( "8" )
  $*9::             PressKeyEvent(   "9" )
  $*9 Up::          ReleaseKeyEvent( "9" )
  $*0::             PressKeyEvent(   "0" )
  $*0 Up::          ReleaseKeyEvent( "0" )
  $*[::             PressKeyEvent(   "[" )
  $*[ Up::          ReleaseKeyEvent( "[" )
  $*]::             PressKeyEvent(   "]" )
  $*] Up::          ReleaseKeyEvent( "]" )
  $*g::             PressKeyEvent(   "g" )
  $*g Up::          ReleaseKeyEvent( "g" )
  $*l::             PressKeyEvent(   "l" )
  $*l Up::          ReleaseKeyEvent( "l" )
  $*c::             PressKeyEvent(   "c" )
  $*c Up::          ReleaseKeyEvent( "c" )
  $*r::             PressKeyEvent(   "r" )
  $*r Up::          ReleaseKeyEvent( "r" )
  $*h::             PressKeyEvent(   "h" )
  $*h Up::          ReleaseKeyEvent( "h" )
  $*s::             PressKeyEvent(   "s" )
  $*s Up::          ReleaseKeyEvent( "s" )
  $*t::             PressKeyEvent(   "t" )
  $*t Up::          ReleaseKeyEvent( "t" )
  $*n::             PressKeyEvent(   "n" )
  $*n Up::          ReleaseKeyEvent( "n" )
  $*d::             PressKeyEvent(   "d" )
  $*d Up::          ReleaseKeyEvent( "d" )
  $*-::             PressKeyEvent(   "-" )
  $*- Up::          ReleaseKeyEvent( "-" )
  $*f::             PressKeyEvent(   "f" )
  $*f Up::          ReleaseKeyEvent( "f" )
  $*Delete::        PressKeyEvent(   "Delete" )
  $*Delete Up::     ReleaseKeyEvent( "Delete" )
  $*Backspace::     PressKeyEvent(   "Backspace" )
  $*Backspace Up::  ReleaseKeyEvent( "Backspace" )
  $*/::             PressKeyEvent(   "/" )
  $*/ Up::          ReleaseKeyEvent( "/" )
  $*=::             PressKeyEvent(   "=" )
  $*= Up::          ReleaseKeyEvent( "=" )
  $*\::             PressKeyEvent(   "\\" )
  $*\ Up::          ReleaseKeyEvent( "\\" )
  $*Enter::         PressKeyEvent(   "Enter" )
  $*Enter Up::      ReleaseKeyEvent( "Enter" )
  $*Space::         PressKeyEvent(   "Space" )
  $*Space Up::      ReleaseKeyEvent( "Space" )
  $*b::             PressKeyEvent(   "b" )
  $*b Up::          ReleaseKeyEvent( "b" )
  $*m::             PressKeyEvent(   "m" )
  $*m Up::          ReleaseKeyEvent( "m" )
  $*w::             PressKeyEvent(   "w" )
  $*w Up::          ReleaseKeyEvent( "w" )
  $*v::             PressKeyEvent(   "v" )
  $*v Up::          ReleaseKeyEvent( "v" )
  $*z::             PressKeyEvent(   "z" )
  $*z Up::          ReleaseKeyEvent( "z" )

  ; Movement
  $*Left::          PressKeyEvent(   "Left" )
  $*Left Up::       ReleaseKeyEvent( "Left" )
  $*Right::         PressKeyEvent(   "Right" )
  $*Right Up::      ReleaseKeyEvent( "Right" )
  $*Up::            PressKeyEvent(   "Up" )
  $*Up Up::         ReleaseKeyEvent( "Up" )
  $*Down::          PressKeyEvent(   "Down" )
  $*Down Up::       ReleaseKeyEvent( "Down" )
  $*End::           PressKeyEvent(   "End" )
  $*End Up::        ReleaseKeyEvent( "End" )
  $*Home::          PressKeyEvent(   "Home" )
  $*Home Up::       ReleaseKeyEvent( "Home" )
  $*PgUp::          PressKeyEvent(   "PgUp" )
  $*PgUp Up::       ReleaseKeyEvent( "PgUp" )
  $*PgDn::          PressKeyEvent(   "PgDn" )
  $*PgDn Up::       ReleaseKeyEvent( "PgDn" )

  ; Function Keys
  $*F1::            PressKeyEvent(   "F1" )
  $*F1 Up::         ReleaseKeyEvent( "F1" )
  $*F2::            PressKeyEvent(   "F2" )
  $*F2 Up::         ReleaseKeyEvent( "F2" )
  $*F3::            PressKeyEvent(   "F3" )
  $*F3 Up::         ReleaseKeyEvent( "F3" )
  $*F4::            PressKeyEvent(   "F4" )
  $*F4 Up::         ReleaseKeyEvent( "F4" )
  $*F5::            PressKeyEvent(   "F5" )
  $*F5 Up::         ReleaseKeyEvent( "F5" )
  $*F6::            PressKeyEvent(   "F6" )
  $*F6 Up::         ReleaseKeyEvent( "F6" )
  $*F7::            PressKeyEvent(   "F7" )
  $*F7 Up::         ReleaseKeyEvent( "F7" )
  $*F8::            PressKeyEvent(   "F8" )
  $*F8 Up::         ReleaseKeyEvent( "F8" )
  $*F9::            PressKeyEvent(   "F9" )
  $*F9 Up::         ReleaseKeyEvent( "F9" )
  $*F10::           PressKeyEvent(   "F10" )
  $*F10 Up::        ReleaseKeyEvent( "F10" )
  $*F11::           PressKeyEvent(   "F11" )
  $*F11 Up::        ReleaseKeyEvent( "F11" )
  $*F12::           PressKeyEvent(   "F12" )
  $*F12 Up::        ReleaseKeyEvent( "F12" )

