
; Modifiers
  $*LControl::      KeyPressEvent(   "LControl" )
  $*LControl Up::   KeyReleaseEvent( "LControl" )
  $*LShift::        KeyPressEvent(   "LShift" )
  $*LShift Up::     KeyReleaseEvent( "LShift" )
  $*LAlt::          KeyPressEvent(   "LAlt" )
  $*LAlt Up::       KeyReleaseEvent( "LAlt" )
  $*LWin::          KeyPressEvent(   "LWin" )
  $*LWin Up::       KeyReleaseEvent( "LWin" )
  $*RControl::      KeyPressEvent(   "RControl" )
  $*RControl Up::   KeyReleaseEvent( "RControl" )
  $*RShift::        KeyPressEvent(   "RShift" )
  $*RShift Up::     KeyReleaseEvent( "RShift" )
  $*RAlt::          KeyPressEvent(   "RAlt" )
  $*RAlt Up::       KeyReleaseEvent( "RAlt" )


; Normal Keys
  ; Left Hand
  $*Escape::        KeyPressEvent(   "Escape" )
  $*Escape Up::     KeyReleaseEvent( "Escape" )
  $*`::             KeyPressEvent(   "Backtick" )
  $*` Up::          KeyReleaseEvent( "Backtick" )
  $*Tab::           KeyPressEvent(   "Tab" )
  $*Tab Up::        KeyReleaseEvent( "Tab" )
  $*1::             KeyPressEvent(   "1" )
  $*1 Up::          KeyReleaseEvent( "1" )
  $*2::             KeyPressEvent(   "2" )
  $*2 Up::          KeyReleaseEvent( "2" )
  $*3::             KeyPressEvent(   "3" )
  $*3 Up::          KeyReleaseEvent( "3" )
  $*4::             KeyPressEvent(   "4" )
  $*4 Up::          KeyReleaseEvent( "4" )
  $*5::             KeyPressEvent(   "5" )
  $*5 Up::          KeyReleaseEvent( "5" )
  $*6::             KeyPressEvent(   "6" )
  $*6 Up::          KeyReleaseEvent( "6" )
  $*'::             KeyPressEvent(   "Apostrophe" )
  $*' Up::          KeyReleaseEvent( "Apostrophe" )
  $*,::             KeyPressEvent(   "Comma" )
  $*, Up::          KeyReleaseEvent( "Comma" )
  $*.::             KeyPressEvent(   "Dot" )
  $*. Up::          KeyReleaseEvent( "Dot" )
  $*p::             KeyPressEvent(   "p" )
  $*p Up::          KeyReleaseEvent( "p" )
  $*y::             KeyPressEvent(   "y" )
  $*y Up::          KeyReleaseEvent( "y" )
  $*a::             KeyPressEvent(   "a" )
  $*a Up::          KeyReleaseEvent( "a" )
  $*o::             KeyPressEvent(   "o" )
  $*o Up::          KeyReleaseEvent( "o" )
  $*e::             KeyPressEvent(   "e" )
  $*e Up::          KeyReleaseEvent( "e" )
  $*u::             KeyPressEvent(   "u" )
  $*u Up::          KeyReleaseEvent( "u" )
  $*i::             KeyPressEvent(   "i" )
  $*i Up::          KeyReleaseEvent( "i" )
  $*;::             KeyPressEvent(   "Semicolon" )
  $*; Up::          KeyReleaseEvent( "Semicolon" )
  $*q::             KeyPressEvent(   "q" )
  $*q Up::          KeyReleaseEvent( "q" )
  $*j::             KeyPressEvent(   "j" )
  $*j Up::          KeyReleaseEvent( "j" )
  $*k::             KeyPressEvent(   "k" )
  $*k Up::          KeyReleaseEvent( "k" )
  $*x::             KeyPressEvent(   "x" )
  $*x Up::          KeyReleaseEvent( "x" )

  ; Right Hand
  $*7::             KeyPressEvent(   "7" )
  $*7 Up::          KeyReleaseEvent( "7" )
  $*8::             KeyPressEvent(   "8" )
  $*8 Up::          KeyReleaseEvent( "8" )
  $*9::             KeyPressEvent(   "9" )
  $*9 Up::          KeyReleaseEvent( "9" )
  $*0::             KeyPressEvent(   "Zero" )
  $*0 Up::          KeyReleaseEvent( "Zero" )
  $*[::             KeyPressEvent(   "OpenBracket" )
  $*[ Up::          KeyReleaseEvent( "OpenBracket" )
  $*]::             KeyPressEvent(   "CloseBracket" )
  $*] Up::          KeyReleaseEvent( "CloseBracket" )
  $*g::             KeyPressEvent(   "g" )
  $*g Up::          KeyReleaseEvent( "g" )
  $*l::             KeyPressEvent(   "l" )
  $*l Up::          KeyReleaseEvent( "l" )
  $*c::             KeyPressEvent(   "c" )
  $*c Up::          KeyReleaseEvent( "c" )
  $*r::             KeyPressEvent(   "r" )
  $*r Up::          KeyReleaseEvent( "r" )
  $*h::             KeyPressEvent(   "h" )
  $*h Up::          KeyReleaseEvent( "h" )
  $*s::             KeyPressEvent(   "s" )
  $*s Up::          KeyReleaseEvent( "s" )
  $*t::             KeyPressEvent(   "t" )
  $*t Up::          KeyReleaseEvent( "t" )
  $*n::             KeyPressEvent(   "n" )
  $*n Up::          KeyReleaseEvent( "n" )
  $*d::             KeyPressEvent(   "d" )
  $*d Up::          KeyReleaseEvent( "d" )
  $*-::             KeyPressEvent(   "Dash" )
  $*- Up::          KeyReleaseEvent( "Dash" )
  $*f::             KeyPressEvent(   "f" )
  $*f Up::          KeyReleaseEvent( "f" )
  $*Delete::        KeyPressEvent(   "Delete" )
  $*Delete Up::     KeyReleaseEvent( "Delete" )
  $*Backspace::     KeyPressEvent(   "Backspace" )
  $*Backspace Up::  KeyReleaseEvent( "Backspace" )
  $*/::             KeyPressEvent(   "Forwardslash" )
  $*/ Up::          KeyReleaseEvent( "Forwardslash" )
  $*=::             KeyPressEvent(   "Equals" )
  $*= Up::          KeyReleaseEvent( "Equals" )
  $*\::             KeyPressEvent(   "Backslash" )
  $*\ Up::          KeyReleaseEvent( "Backslash" )
  $*Enter::         KeyPressEvent(   "Enter" )
  $*Enter Up::      KeyReleaseEvent( "Enter" )
  $*Space::         KeyPressEvent(   "Space" )
  $*Space Up::      KeyReleaseEvent( "Space" )
  $*b::             KeyPressEvent(   "b" )
  $*b Up::          KeyReleaseEvent( "b" )
  $*m::             KeyPressEvent(   "m" )
  $*m Up::          KeyReleaseEvent( "m" )
  $*w::             KeyPressEvent(   "w" )
  $*w Up::          KeyReleaseEvent( "w" )
  $*v::             KeyPressEvent(   "v" )
  $*v Up::          KeyReleaseEvent( "v" )
  $*z::             KeyPressEvent(   "z" )
  $*z Up::          KeyReleaseEvent( "z" )

  ; Movement
  $*Left::          KeyPressEvent(   "Left" )
  $*Left Up::       KeyReleaseEvent( "Left" )
  $*Right::         KeyPressEvent(   "Right" )
  $*Right Up::      KeyReleaseEvent( "Right" )
  $*Up::            KeyPressEvent(   "Up" )
  $*Up Up::         KeyReleaseEvent( "Up" )
  $*Down::          KeyPressEvent(   "Down" )
  $*Down Up::       KeyReleaseEvent( "Down" )
  $*End::           KeyPressEvent(   "End" )
  $*End Up::        KeyReleaseEvent( "End" )
  $*Home::          KeyPressEvent(   "Home" )
  $*Home Up::       KeyReleaseEvent( "Home" )
  $*PgUp::          KeyPressEvent(   "PgUp" )
  $*PgUp Up::       KeyReleaseEvent( "PgUp" )
  $*PgDn::          KeyPressEvent(   "PgDn" )
  $*PgDn Up::       KeyReleaseEvent( "PgDn" )
